"use client";
import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'ru';
type TranslationKey = keyof typeof translations.en | keyof typeof translations.ru;

type LanguageContextType = {
    language: Language;
    setLanguage: (language: Language) => void;
    t: (key: string) => string;
};

const translations = {
    en: {
        'nav.generate': 'Generate',
        'nav.prompt_library': 'Prompt Library',
        'nav.community': 'Community',
        'nav.favorites': 'Favorites',
        'nav.history': 'History',
        'nav.learning': 'Learning',
        'nav.about': 'About',
        'nav.settings': 'Settings',
        'nav.sign_in': 'Sign In',
        'community.no_artworks_found': 'No artworks found',
        'header.ai_models': 'AI Models: Online',
        'header.credits': 'credits',
        'header.notifications': 'Notifications',
        'header.no_notifications': 'No notifications',
        'header.view_all_notifications': 'View all notifications',
        'generation.title': 'Create New Image',
        'generation.image_settings': 'Image Settings',
        'generation.configure_parameters': 'Configure your generation parameters',
        'generation.basic': 'Basic',
        'generation.advanced': 'Advanced',
        'generation.prompt': 'Prompt',
        'generation.ai_enhance': 'AI Enhance',
        'generation.prompt_placeholder': 'Describe your image in detail... (e.g., A serene landscape with mountains, a calm lake under twilight sky with stars beginning to appear)',
        'generation.suggestions': 'Suggestions',
        'generation.save_prompt': 'Save Prompt',
        'generation.negative_prompt': 'Negative Prompt',
        'generation.negative_prompt_placeholder': 'Elements to avoid in the image... (e.g., blurry, bad anatomy, distorted, watermark, signature)',
        'generation.model_selection': 'Model Selection',
        'generation.seed': 'Seed',
        'generation.sampling_steps': 'Sampling Steps',
        'generation.cfg_scale': 'CFG Scale',
        'generation.sampler': 'Sampler',
        'generation.image_to_image': 'Image to Image',
        'generation.upload_image': 'Click to upload an image',
        'generation.generating': 'Generating...',
        'generation.generate': 'Generate',
        'generation.preview': 'Preview',
        'generation.your_image_will_appear': 'Your generated image will appear here',
        'generation.enter_prompt': 'Start by entering a detailed prompt',
        'generation.creating_masterpiece': 'Creating your masterpiece...',
        'generation.analyzing_prompt': 'Analyzing prompt...',
        'generation.generating_composition': 'Generating base composition...',
        'generation.adding_details': 'Adding details and refining...',
        'generation.finalizing': 'Finalizing image...',
        'generation.save': 'Save',
        'generation.share': 'Share',
        'generation.download': 'Download',
        'generation.variations': 'Variations',
        'generation.favorite': 'Favorite',
        'generation.share_community': 'Share to Community',
        'generation.open_workflow': 'Open Visual Workflow Editor',
        'ui.aspect_ratio': 'Aspect Ratio',
        'ui.square': 'Square',
        'ui.standard': 'Standard',
        'ui.widescreen': 'Widescreen',
        'ui.portrait': 'Portrait',
        'ui.landscape': 'Landscape',

        // Additional translations for optimized generation form
        'generation.tag.add': 'Add Tag',
        'generation.model.flux': 'Flux Realistic',
        'generation.model.anime': 'Anime Diffusion',
        'generation.model.dream': 'Dreamshaper',
        'generation.model.real': 'Realistic Vision',
        'generation.ai_enhance.tooltip': 'Let AI enhance your prompt with additional details',
        'generation.resolution': 'Resolution',
        'generation.batch_count': 'Batch Count',
        'generation.tag.suggestions': 'Suggested Tags',
        'generation.upscaler': 'Upscaler',
        'generation.vae': 'VAE Model',
        'generation.lora.add': 'Add LoRA',
        'generation.lora.weight': 'Weight',

        'login.title': 'Sign in to VisioMera',
        'login.description': 'Enter your email and password to access your account',
        'login.email': 'Email',
        'login.password': 'Password',
        'login.forgot_password': 'Forgot password?',
        'login.sign_in': 'Sign In',
        'login.register': 'Register',
        'login.name': 'Name',
        'login.confirm_password': 'Confirm Password',
        'login.create_account': 'Create Account',
        'login.or_continue_with': 'Or continue with',
        'login.terms_agreement': 'By signing in, you agree to our',
        'login.terms_of_service': 'Terms of Service',
        'login.and': 'and',
        'login.privacy_policy': 'Privacy Policy',
        'settings.title': 'Settings',
        'settings.description': 'Manage your account preferences and application settings',
        'settings.tab.account': 'Account',
        'settings.tab.appearance': 'Appearance',
        'settings.tab.notifications': 'Notifications',
        'settings.tab.subscription': 'Subscription',
        'settings.tab.privacy': 'Privacy',
        'settings.tab.api': 'API',
        'settings.profile.title': 'Profile Information',
        'settings.profile.description': 'Manage your account details and public profile',
        'settings.profile.display_name': 'Display Name',
        'settings.profile.username': 'Username',
        'settings.profile.email': 'Email',
        'settings.profile.bio': 'Bio',
        'settings.profile.edit': 'Edit Profile',
        'settings.profile.cancel': 'Cancel',
        'settings.profile.save': 'Save Changes',
        'settings.profile.change_avatar': 'Change Avatar',
        'settings.security.title': 'Account Security',
        'settings.security.description': 'Manage your password and security settings',
        'settings.security.current_password': 'Current Password',
        'settings.security.new_password': 'New Password',
        'settings.security.confirm_password': 'Confirm New Password',
        'settings.security.2fa': 'Two-Factor Authentication',
        'settings.security.2fa_app': 'Authenticator App',
        'settings.security.recommended': 'Recommended',
        'settings.security.2fa_description': 'Use an authenticator app to get two-factor authentication codes',
        'settings.security.enable': 'Enable',
        'settings.security.update': 'Update Security Settings',
        'settings.danger.title': 'Danger Zone',
        'settings.danger.description': 'Irreversible account actions',
        'settings.danger.delete_account': 'Delete Account',
        'settings.danger.delete_warning': 'Once you delete your account, there is no going back. This action cannot be undone.',
        'community.title': 'Community Hub',
        'community.subtitle': 'Explore creations from the VisioMera community',
        'community.search': 'Search artworks...',
        'community.new_collection': 'New Collection',
        'community.upload': 'Upload Creation',
        'community.featured': 'Featured',
        'community.days_ago': 'days ago',
        'community.hours_ago': 'hours ago',
        'community.just_now': 'Just now',
        'community.view_all': 'View all',
        'community.search_placeholder': 'Search artworks...',
        'community.grid_view': 'Grid View',
        'community.list_view': 'List View',
        'community.filters': 'Filters',
        'community.newest': 'Newest',
        'community.trending': 'Trending',
        'community.popular': 'Popular',
        'community.category': 'Category',
        'community.select_category': 'Select category',
        'community.all_categories': 'All Categories',
        'community.portrait': 'Portrait',
        'community.landscape': 'Landscape',
        'community.abstract': 'Abstract',
        'community.fantasy': 'Fantasy',
        'community.animals': 'Animals',
        'community.architecture': 'Architecture',
        'community.art': 'Art',
        'community.other': 'Other',
        'community.model_type': 'Model Type',
        'community.select_model': 'Select model',
        'community.all_models': 'All Models',
        'community.other_models': 'Other Models',
        'community.time_range': 'Time Range',
        'community.select_time': 'Select time range',
        'community.all_time': 'All Time',
        'community.today': 'Today',
        'community.this_week': 'This Week',
        'community.this_month': 'This Month',
        'history.title': 'Generation History',
        'history.subtitle': 'View and manage your previous generations',
        'history.recent': 'Recent Generations',
        'history.search': 'Search history...',
        'history.filter': 'Filter by',
        'history.all': 'All Images',
        'history.saved': 'Saved Only',
        'history.shared': 'Shared Only',
        'history.grid': 'Grid View',
        'history.list': 'List View',
        'history.export': 'Export History',
        'history.load_more': 'Load More',
        'history.page_title': 'My Generation History',
        'history.page_subtitle': 'Browse and manage your previous image generations',
        'history.search_placeholder': 'Search in history...',
        'history.filter_by': 'Filter by',
        'history.all_images': 'All Images',
        'history.saved_only': 'Saved Only',
        'history.shared_only': 'Shared Only',
        'history.grid_view': 'Grid View',
        'history.list_view': 'List View',
        'history.today': 'Today',
        'history.yesterday': 'Yesterday',
        'history.untitled': 'Untitled',
        'history.public': 'Public',
        'history.view_image': 'View Image',
        'history.download': 'Download',
        'history.delete_image': 'Delete Image',
        'history.confirm_delete': 'Confirm Deletion',
        'history.delete_confirmation': 'Are you sure you want to delete this image? This action cannot be undone.',
        'history.no_artworks_found': 'No artworks found in your history',
        'favorites.title': 'Favorites',
        'favorites.subtitle': 'Organize and manage your saved images',
        'favorites.search': 'Search favorites...',
        'favorites.collections': 'Collections',
        'favorites.create': 'Create Collection',
        'favorites.collection_name': 'Collection Name',
        'favorites.description': 'Description (Optional)',
        'favorites.all_favorites': 'All Favorites',
        'favorites.recently': 'Recently Favorited',
        'favorites.page_title': 'My Favorites',
        'favorites.page_subtitle': 'Browse and manage your favorite artworks',
        'favorites.my_collections': 'My Collections',
        'favorites.new_collection': 'New Collection',
        'favorites.create_collection': 'Create Collection',
        'favorites.create_collection_description': 'Create a new collection to organize your favorite artworks',
        'favorites.collection_name_placeholder': 'Enter collection name',
        'favorites.collection_description_placeholder': 'Enter collection description (optional)',
        'favorites.no_collections': 'No Collections Yet',
        'favorites.create_first_collection': 'Create your first collection to organize your favorite artworks',
        'favorites.liked_artworks': 'Liked Artworks',
        'favorites.no_favorites': 'No Favorites Yet',
        'favorites.like_artworks': 'Like artworks to see them here',
        'favorites.view': 'View',
        'favorites.edit': 'Edit',
        'favorites.delete': 'Delete',
        'favorites.confirm_delete': 'Confirm Deletion',
        'favorites.delete_confirmation': 'Are you sure you want to delete this collection? This action cannot be undone.',
        'favorites.item': 'item',
        'favorites.items': 'items',
        'common.cancel': 'Cancel',
        'common.delete': 'Delete',
        'about.title': 'About VisioMera',
        'about.subtitle': 'Empowering creativity through AI art generation',
        'about.mission.title': 'Our Mission',
        'about.mission.text1': 'VisioMera was created to democratize digital art creation by making powerful AI tools accessible to everyone. We believe that creativity should not be limited by technical skill, but rather enhanced by technology that helps bring your imagination to life.',
        'about.mission.text2': 'Our platform combines the power of ComfyUI, Flux models, and other cutting-edge AI technologies to provide an intuitive yet powerful interface for creating stunning visual art.',
        'about.developer.title': 'Meet the Developer',
        'about.developer.name': 'Proxy Nihil',
        'about.developer.bio': 'Proxy Nihil is a developer and AI enthusiast passionate about the intersection of technology and creativity. With a background in computer science and digital art, they created VisioMera to bridge the gap between technical complexity and artistic expression.',
        'about.timeline.title': 'Development Timeline',
        'about.timeline.event1.date': 'March 2025',
        'about.timeline.event1.title': 'VisioMera Launch',
        'about.timeline.event1.description': 'Initial release with core generation features and community hub.',
        'about.timeline.event2.date': 'January 2025',
        'about.timeline.event2.title': 'Beta Testing',
        'about.timeline.event2.description': 'Invited users test the platform and provide feedback for improvements.',
        'about.timeline.event3.date': 'October 2024',
        'about.timeline.event3.title': 'Development Begins',
        'about.timeline.event3.description': 'Work starts on creating a user-friendly interface for ComfyUI and Flux models.',
        'about.timeline.event4.date': 'August 2024',
        'about.timeline.event4.title': 'Concept Phase',
        'about.timeline.event4.description': 'Research and planning for an accessible AI art generation platform.',
        'about.tech.title': 'Technology Stack',
        'about.tech.comfy.title': 'ComfyUI',
        'about.tech.comfy.description': 'A powerful and modular UI system for Stable Diffusion and other generative models.',
        'about.tech.flux.title': 'Flux Models',
        'about.tech.flux.description': 'State-of-the-art image generation models optimized for quality and speed.',
        'about.tech.nextjs.title': 'Next.js',
        'about.tech.nextjs.description': 'React framework for building fast and responsive web applications.',
        'about.tech.tailwind.title': 'Tailwind CSS',
        'about.tech.tailwind.description': 'Utility-first CSS framework for rapid UI development.',
        'about.faq.title': 'Frequently Asked Questions',
        'about.contact.title': 'Contact Us',
        'about.contact.name': 'Name',
        'about.contact.email': 'Email',
        'about.contact.subject': 'Subject',
        'about.contact.message': 'Message',
        'about.contact.send': 'Send Message',
        'prompts.title': 'Prompt Library',
        'prompts.subtitle': 'Manage, organize, and share your AI image generation prompts',
        'prompts.search': 'Search prompts...',
        'prompts.new': 'New Prompt',
        'prompts.edit': 'Edit',
        'prompts.delete': 'Delete',
        'prompts.save': 'Save',
        'prompts.use': 'Use Prompt',
        'prompts.copy': 'Copy Prompt',
        'prompts.share': 'Share',
        'prompts.favorite': 'Favorite',
        'prompts.unfavorite': 'Unfavorite',
    },
    ru: {
        'nav.generate': 'Создать',
        'nav.prompt_library': 'Библиотека промптов',
        'nav.community': 'Сообщество',
        'nav.favorites': 'Избранное',
        'nav.history': 'История',
        'nav.learning': 'Обучение',
        'nav.about': 'О нас',
        'nav.settings': 'Настройки',
        'nav.sign_in': 'Войти',
        'community.no_artworks_found': 'Работы не найдены',
        'header.ai_models': 'ИИ Модели: Онлайн',
        'header.credits': 'кредитов',
        'header.notifications': 'Уведомления',
        'header.no_notifications': 'Нет уведомлений',
        'header.view_all_notifications': 'Посмотреть все уведомления',
        'generation.title': 'Создать новое изображение',
        'generation.image_settings': 'Настройки изображения',
        'generation.configure_parameters': 'Настройка параметров генерации',
        'generation.basic': 'Основные',
        'generation.advanced': 'Расширенные',
        'generation.prompt': 'Промпт',
        'generation.ai_enhance': 'ИИ улучшение',
        'generation.prompt_placeholder': 'Опишите ваше изображение подробно... (например, Спокойный пейзаж с горами, тихое озеро в сумерках с появляющимися звездами)',
        'generation.suggestions': 'Подсказки',
        'generation.save_prompt': 'Сохранить промпт',
        'generation.negative_prompt': 'Негативный промпт',
        'generation.negative_prompt_placeholder': 'Элементы, которых следует избегать в изображении... (например, размытость, плохая анатомия, искажения, водяной знак, подпись)',
        'generation.model_selection': 'Выбор модели',
        'generation.seed': 'Сид',
        'generation.sampling_steps': 'Шаги сэмплирования',
        'generation.cfg_scale': 'CFG масштаб',
        'generation.sampler': 'Сэмплер',
        'generation.image_to_image': 'Изображение в изображение',
        'generation.upload_image': 'Нажмите, чтобы загрузить изображение',
        'generation.generating': 'Генерация...',
        'generation.generate': 'Сгенерировать',
        'generation.preview': 'Предпросмотр',
        'generation.your_image_will_appear': 'Ваше изображение появится здесь',
        'generation.enter_prompt': 'Начните с ввода подробного промпта',
        'generation.creating_masterpiece': 'Создаем ваш шедевр...',
        'generation.analyzing_prompt': 'Анализ промпта...',
        'generation.generating_composition': 'Создание базовой композиции...',
        'generation.adding_details': 'Добавление деталей и уточнение...',
        'generation.finalizing': 'Финализация изображения...',
        'generation.save': 'Сохранить',
        'generation.share': 'Поделиться',
        'generation.download': 'Скачать',
        'generation.variations': 'Вариации',
        'generation.favorite': 'В избранное',
        'generation.share_community': 'Поделиться с сообществом',
        'generation.open_workflow': 'Открыть визуальный редактор воркфлоу',
        'ui.aspect_ratio': 'Соотношение сторон',
        'ui.square': 'Квадрат',
        'ui.standard': 'Стандарт',
        'ui.widescreen': 'Широкоэкранный',
        'ui.portrait': 'Портрет',
        'ui.landscape': 'Пейзаж',

        // Additional translations for optimized generation form
        'generation.tag.add': 'Добавить тег',
        'generation.model.flux': 'Flux Реалистичный',
        'generation.model.anime': 'Anime Диффузия',
        'generation.model.dream': 'Dreamshaper',
        'generation.model.real': 'Realistic Vision',
        'generation.ai_enhance.tooltip': 'Позвольте ИИ улучшить ваш промпт дополнительными деталями',
        'generation.resolution': 'Разрешение',
        'generation.batch_count': 'Количество в партии',
        'generation.tag.suggestions': 'Предлагаемые теги',
        'generation.upscaler': 'Апскейлер',
        'generation.vae': 'Модель VAE',
        'generation.lora.add': 'Добавить LoRA',
        'generation.lora.weight': 'Вес',

        'login.title': 'Вход в ВизиоМера',
        'login.description': 'Введите ваш email и пароль для доступа к аккаунту',
        'login.email': 'Email',
        'login.password': 'Пароль',
        'login.forgot_password': 'Забыли пароль?',
        'login.sign_in': 'Войти',
        'login.register': 'Регистрация',
        'login.name': 'Имя',
        'login.confirm_password': 'Подтвердите пароль',
        'login.create_account': 'Создать аккаунт',
        'login.or_continue_with': 'Или продолжить с помощью',
        'login.terms_agreement': 'Входя в систему, вы соглашаетесь с нашими',
        'login.terms_of_service': 'Условиями использования',
        'login.and': 'и',
        'login.privacy_policy': 'Политикой конфиденциальности',
        'settings.title': 'Настройки',
        'settings.description': 'Управление предпочтениями аккаунта и настройками приложения',
        'settings.tab.account': 'Аккаунт',
        'settings.tab.appearance': 'Внешний вид',
        'settings.tab.notifications': 'Уведомления',
        'settings.tab.subscription': 'Подписка',
        'settings.tab.privacy': 'Приватность',
        'settings.tab.api': 'API',
        'settings.profile.title': 'Информация профиля',
        'settings.profile.description': 'Управление данными вашего аккаунта и публичного профиля',
        'settings.profile.display_name': 'Отображаемое имя',
        'settings.profile.username': 'Имя пользователя',
        'settings.profile.email': 'Email',
        'settings.profile.bio': 'О себе',
        'settings.profile.edit': 'Редактировать профиль',
        'settings.profile.cancel': 'Отмена',
        'settings.profile.save': 'Сохранить изменения',
        'settings.profile.change_avatar': 'Изменить аватар',
        'settings.security.title': 'Безопасность аккаунта',
        'settings.security.description': 'Управление паролем и настройками безопасности',
        'settings.security.current_password': 'Текущий пароль',
        'settings.security.new_password': 'Новый пароль',
        'settings.security.confirm_password': 'Подтвердите новый пароль',
        'settings.security.2fa': 'Двухфакторная аутентификация',
        'settings.security.2fa_app': 'Приложение-аутентификатор',
        'settings.security.recommended': 'Рекомендуется',
        'settings.security.2fa_description': 'Используйте приложение-аутентификатор для получения кодов двухфакторной аутентификации',
        'settings.security.enable': 'Включить',
        'settings.security.update': 'Обновить настройки безопасности',
        'settings.danger.title': 'Опасная зона',
        'settings.danger.description': 'Необратимые действия с аккаунтом',
        'settings.danger.delete_account': 'Удалить аккаунт',
        'settings.danger.delete_warning': 'После удаления аккаунта пути назад нет. Это действие нельзя отменить.',
        'community.title': 'Сообщество',
        'community.subtitle': 'Исследуйте работы сообщества ВизиоМера',
        'community.search': 'Поиск работ...',
        'community.new_collection': 'Новая коллекция',
        'community.upload': 'Загрузить работу',
        'community.featured': 'Рекомендуемые',
        'community.days_ago': 'дней назад',
        'community.hours_ago': 'часов назад',
        'community.just_now': 'Только что',
        'community.view_all': 'Показать все',
        'community.search_placeholder': 'Поиск работ...',
        'community.grid_view': 'Вид сеткой',
        'community.list_view': 'Вид списком',
        'community.filters': 'Фильтры',
        'community.newest': 'Новые',
        'community.trending': 'Популярные',
        'community.popular': 'Лучшие',
        'community.category': 'Категория',
        'community.select_category': 'Выберите категорию',
        'community.all_categories': 'Все категории',
        'community.portrait': 'Портрет',
        'community.landscape': 'Пейзаж',
        'community.abstract': 'Абстракция',
        'community.fantasy': 'Фэнтези',
        'community.animals': 'Животные',
        'community.architecture': 'Архитектура',
        'community.art': 'Искусство',
        'community.other': 'Другое',
        'community.model_type': 'Тип модели',
        'community.select_model': 'Выберите модель',
        'community.all_models': 'Все модели',
        'community.other_models': 'Другие модели',
        'community.time_range': 'Временной диапазон',
        'community.select_time': 'Выберите период',
        'community.all_time': 'За все время',
        'community.today': 'Сегодня',
        'community.this_week': 'На этой неделе',
        'community.this_month': 'В этом месяце',
        'history.title': 'История генерации',
        'history.subtitle': 'Просмотр и управление вашими предыдущими генерациями',
        'history.recent': 'Недавние генерации',
        'history.search': 'Поиск в истории...',
        'history.filter': 'Фильтровать по',
        'history.all': 'Все изображения',
        'history.saved': 'Только сохраненные',
        'history.shared': 'Только опубликованные',
        'history.grid': 'Сетка',
        'history.list': 'Список',
        'history.export': 'Экспорт истории',
        'history.load_more': 'Загрузить еще',
        'history.page_title': 'Моя история генераций',
        'history.page_subtitle': 'Просмотр и управление вашими предыдущими генерациями изображений',
        'history.search_placeholder': 'Поиск в истории...',
        'history.filter_by': 'Фильтровать по',
        'history.all_images': 'Все изображения',
        'history.saved_only': 'Только сохраненные',
        'history.shared_only': 'Только опубликованные',
        'history.grid_view': 'Вид сеткой',
        'history.list_view': 'Вид списком',
        'history.today': 'Сегодня',
        'history.yesterday': 'Вчера',
        'history.untitled': 'Без названия',
        'history.public': 'Публичное',
        'history.view_image': 'Просмотр изображения',
        'history.download': 'Скачать',
        'history.delete_image': 'Удалить изображение',
        'history.confirm_delete': 'Подтвердите удаление',
        'history.delete_confirmation': 'Вы уверены, что хотите удалить это изображение? Это действие нельзя отменить.',
        'history.no_artworks_found': 'В вашей истории не найдено работ',
        'favorites.title': 'Избранное',
        'favorites.subtitle': 'Организуйте и управляйте вашими сохраненными изображениями',
        'favorites.search': 'Поиск в избранном...',
        'favorites.collections': 'Коллекции',
        'favorites.create': 'Создать коллекцию',
        'favorites.collection_name': 'Название коллекции',
        'favorites.description': 'Описание (опционально)',
        'favorites.all_favorites': 'Все избранное',
        'favorites.recently': 'Недавно добавленные',
        'favorites.page_title': 'Моё избранное',
        'favorites.page_subtitle': 'Просмотр и управление избранными работами',
        'favorites.my_collections': 'Мои коллекции',
        'favorites.new_collection': 'Новая коллекция',
        'favorites.create_collection': 'Создать коллекцию',
        'favorites.create_collection_description': 'Создайте новую коллекцию для организации ваших избранных работ',
        'favorites.collection_name_placeholder': 'Введите название коллекции',
        'favorites.collection_description_placeholder': 'Введите описание коллекции (опционально)',
        'favorites.no_collections': 'Пока нет коллекций',
        'favorites.create_first_collection': 'Создайте вашу первую коллекцию для организации избранных работ',
        'favorites.liked_artworks': 'Понравившиеся работы',
        'favorites.no_favorites': 'Пока нет избранного',
        'favorites.like_artworks': 'Отмечайте работы, чтобы видеть их здесь',
        'favorites.view': 'Просмотр',
        'favorites.edit': 'Редактировать',
        'favorites.delete': 'Удалить',
        'favorites.confirm_delete': 'Подтвердите удаление',
        'favorites.delete_confirmation': 'Вы уверены, что хотите удалить эту коллекцию? Это действие нельзя отменить.',
        'favorites.item': 'элемент',
        'favorites.items': 'элементов',
        'common.cancel': 'Отмена',
        'common.delete': 'Удалить',
        'about.title': 'О ВизиоМера',
        'about.subtitle': 'Расширение возможностей творчества с помощью ИИ-генерации изображений',
        'about.mission.title': 'Наша миссия',
        'about.mission.text1': 'ВизиоМера создана для демократизации цифрового искусства, делая мощные инструменты ИИ доступными для всех. Мы считаем, что творчество не должно ограничиваться техническими навыками, а должно усиливаться технологиями, которые помогают воплотить ваше воображение в жизнь.',
        'about.mission.text2': 'Наша платформа объединяет возможности ComfyUI, моделей Flux и других передовых технологий ИИ, чтобы предоставить интуитивно понятный, но мощный интерфейс для создания потрясающего визуального искусства.',
        'about.developer.title': 'Познакомьтесь с разработчиком',
        'about.developer.name': 'Proxy Nihil',
        'about.developer.bio': 'Proxy Nihil — разработчик и энтузиаст ИИ, увлеченный точкой пересечения технологий и творчества. Имея опыт в компьютерных науках и цифровом искусстве, он создал VisioMera, чтобы преодолеть разрыв между технической сложностью и художественным самовыражением.',
        'about.timeline.title': 'Хронология разработки',
        'about.timeline.event1.date': 'Март 2025',
        'about.timeline.event1.title': 'Запуск ВизиоМера',
        'about.timeline.event1.description': 'Первый выпуск с основными функциями генерации и центром сообщества.',
        'about.timeline.event2.date': 'Январь 2025',
        'about.timeline.event2.title': 'Бета-тестирование',
        'about.timeline.event2.description': 'Приглашенные пользователи тестируют платформу и предоставляют отзывы для улучшений.',
        'about.timeline.event3.date': 'Октябрь 2024',
        'about.timeline.event3.title': 'Начало разработки',
        'about.timeline.event3.description': 'Начата работа по созданию удобного интерфейса для ComfyUI и моделей Flux.',
        'about.timeline.event4.date': 'Август 2024',
        'about.timeline.event4.title': 'Концептуальная фаза',
        'about.timeline.event4.description': 'Исследования и планирование доступной платформы генерации искусства ИИ.',
        'about.tech.title': 'Технологический стек',
        'about.tech.comfy.title': 'ComfyUI',
        'about.tech.comfy.description': 'Мощная и модульная UI-система для Stable Diffusion и других генеративных моделей.',
        'about.tech.flux.title': 'Модели Flux',
        'about.tech.flux.description': 'Современные модели генерации изображений, оптимизированные для качества и скорости.',
        'about.tech.nextjs.title': 'Next.js',
        'about.tech.nextjs.description': 'React-фреймворк для создания быстрых и отзывчивых веб-приложений.',
        'about.tech.tailwind.title': 'Tailwind CSS',
        'about.tech.tailwind.description': 'CSS-фреймворк, основанный на утилитах, для быстрой разработки UI.',
        'about.faq.title': 'Часто задаваемые вопросы',
        'about.contact.title': 'Связаться с нами',
        'about.contact.name': 'Имя',
        'about.contact.email': 'Email',
        'about.contact.subject': 'Тема',
        'about.contact.message': 'Сообщение',
        'about.contact.send': 'Отправить сообщение',
        'prompts.title': 'Библиотека промптов',
        'prompts.subtitle': 'Управляйте, организуйте и делитесь промптами для генерации изображений',
        'prompts.search': 'Поиск промптов...',
        'prompts.new': 'Новый промпт',
        'prompts.edit': 'Редактировать',
        'prompts.delete': 'Удалить',
        'prompts.save': 'Сохранить',
        'prompts.use': 'Использовать промпт',
        'prompts.copy': 'Копировать промпт',
        'prompts.share': 'Поделиться',
        'prompts.favorite': 'В избранное',
        'prompts.unfavorite': 'Убрать из избранного',
    }
} as const;

const LanguageContext = createContext<LanguageContextType>({
    language: 'en',
    setLanguage: () => {},
    t: (key) => key,
});

interface LanguageProviderProps {
    children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
    const [language, setLanguage] = useState<Language>('en');

    useEffect(() => {
        const savedLanguage = localStorage.getItem('language') as Language;
        if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'ru')) {
            setLanguage(savedLanguage);
        } else {
            const browserLanguage = navigator.language.split('-')[0];
            if (browserLanguage === 'ru') {
                setLanguage('ru');
            }
        }
    }, []);

    const handleSetLanguage = (newLanguage: Language) => {
        setLanguage(newLanguage);
        localStorage.setItem('language', newLanguage);
        document.documentElement.lang = newLanguage;
    };

    const t = (key: string): string => {
        if (key in translations[language]) {
            return translations[language][key as keyof typeof translations[typeof language]];
        }
        return key;
    };

    return (
        <LanguageContext.Provider
            value={{
                language,
                setLanguage: handleSetLanguage,
                t,
            }}
        >
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext (LanguageContext);

export const useLocalTranslation = (
    pageTranslations: Record<Language, Record<string, string>>
) => {
    const { language, t } = useLanguage();

    // Используем useMemo вместо useCallback для предотвращения создания новой функции при каждом рендере
    // и исключаем t из зависимостей, так как она не меняется по своей логике
    const localT = React.useMemo(() => {
        return (key: string): string => {
            if (pageTranslations[language] && key in pageTranslations[language]) {
                return pageTranslations[language][key];
            }
            return t(key);
        };
    }, [language, pageTranslations]);

    return { localT, language };
};